In [7]:
import pandas as pd
from pathlib import Path

In [19]:
acrash= Path("Data/Crash_Data.csv")
acrash_df=pd.read_csv(acrash)
acrash_df

C:\Users\Deepika\AppData\Local\Temp\ipykernel_13988\3724133214.py:2: DtypeWarning: Columns (10,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  acrash_df=pd.read_csv(acrash)

,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Bus Involvement,Heavy Rigid Truck Involvement,Articulated Truck Involvement,...,Age,National Remoteness Areas,SA4 Name 2016,National LGA Name 2017,National Road Type,Christmas Period,Easter Period,Age Group,Day of week,Time of day
0,20212133,Vic,9,2021,Sunday,0:30,Single,NaN,NaN,NaN,...,38,Inner Regional Australia,Melbourne - Outer East,Yarra Ranges (S),Arterial Road,No,No,26_to_39,Weekend,Night
1,20214022,SA,9,2021,Saturday,23:31,Multiple,No,No,No,...,28,Major Cities of Australia,Adelaide - North,Playford (C),NaN,No,No,26_to_39,Weekend,Night
2,20212096,Vic,9,2021,Saturday,23:00,Single,NaN,NaN,NaN,...,19,Inner Regional Australia,Hume,Wangaratta (RC),Access road,No,No,17_to_25,Weekend,Night
3,20212145,Vic,9,2021,Saturday,22:25,Single,NaN,NaN,NaN,...,23,Outer Regional Australia,Hume,Wangaratta (RC),Arterial Road,No,No,17_to_25,Weekend,Night
4,20212075,Vic,9,2021,Saturday,5:15,Single,NaN,NaN,NaN,...,46,Major Cities of Australia,Melbourne - South East,Casey (C),Local Road,No,No,40_to_64,Weekend,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52838,19891246,NSW,1,1989,Wednesday,17:05,Single,Yes,NaN,No,...,5,NaN,NaN,NaN,NaN,No,No,0_to_16,Weekday,Day
52839,19895088,WA,1,1989,Monday,6:00,Single,No,NaN,No,...,19,NaN,NaN,NaN,NaN,Yes,No,17_to_25,Weekday,Day
52840,19895088,WA,1,1989,Monday,6:00,Single,No,NaN,No,...,17,NaN,NaN,NaN,NaN,Yes,No,17_to_25,Weekday,Day
52841,19895088,WA,1,1989,Monday,6:00,Single,No,NaN,No,...,17,NaN,NaN,NaN,NaN,Yes,No,17_to_25,Weekday,Day
52842,19896063,Tas,1,1989,Tuesday,12:40,Multiple,No,NaN,No,...,63,NaN,NaN,NaN,NaN,No,No,40_to_64,Weekday,Day

In [36]:
acrash_new=acrash_df[['Crash ID','State', 'Month', 'Year', 'Dayweek', 'Time', 'Crash Type', 'Speed Limit','Road User','Gender','Age','National Remoteness Areas','Age Group','Time of day']]
acrash_new.head()

,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Speed Limit,Road User,Gender,Age,National Remoteness Areas,Age Group,Time of day
0,20212133,Vic,9,2021,Sunday,0:30,Single,NaN,Motorcycle rider,Male,38,Inner Regional Australia,26_to_39,Night
1,20214022,SA,9,2021,Saturday,23:31,Multiple,110,Pedestrian,Female,28,Major Cities of Australia,26_to_39,Night
2,20212096,Vic,9,2021,Saturday,23:00,Single,NaN,Passenger,Male,19,Inner Regional Australia,17_to_25,Night
3,20212145,Vic,9,2021,Saturday,22:25,Single,NaN,Driver,Male,23,Outer Regional Australia,17_to_25,Night
4,20212075,Vic,9,2021,Saturday,5:15,Single,NaN,Motorcycle rider,Male,46,Major Cities of Australia,40_to_64,Night

In [37]:
acrash_new_df = acrash_new.dropna(subset=['Speed Limit','National Remoteness Areas'])

In [38]:
acrash_new_df.reset_index(drop=True)

,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Speed Limit,Road User,Gender,Age,National Remoteness Areas,Age Group,Time of day
0,20214022,SA,9,2021,Saturday,23:31,Multiple,110,Pedestrian,Female,28,Major Cities of Australia,26_to_39,Night
1,20213034,Qld,9,2021,Saturday,4:00,Multiple,100,Motorcycle rider,Male,19,Major Cities of Australia,17_to_25,Night
2,20213092,Qld,9,2021,Saturday,2:00,Single,60,Driver,Male,47,Major Cities of Australia,40_to_64,Night
3,20214053,SA,9,2021,Thursday,21:00,Single,80,Driver,Male,24,Inner Regional Australia,17_to_25,Night
4,20213178,Qld,9,2021,Sunday,21:00,Multiple,50,Motorcycle rider,Male,52,Major Cities of Australia,40_to_64,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6802,20144083,SA,1,2014,Friday,11:10,Multiple,110,Passenger,Male,40,Outer Regional Australia,40_to_64,Day
6803,20145108,WA,1,2014,Wednesday,11:47,Single,100,Motorcycle rider,Male,46,Major Cities of Australia,40_to_64,Day
6804,20144022,SA,1,2014,Monday,9:35,Single,50,Pedestrian,Female,82,Major Cities of Australia,75_or_older,Day
6805,20145072,WA,1,2014,Tuesday,21:30,Single,110,Driver,Male,84,Remote Australia,75_or_older,Night
6806,20144007,SA,1,2014,Tuesday,20:00,Single,50,Pedestrian,Male,82,Major Cities of Australia,75_or_older,Night